//
//  HealthSummaryStrings.h
//  MyChart
//
//  Copyright © 2010-2021 Epic Systems Corporation. All rights reserved.
//
#import "WPLocaleInfo.h"

#define STR_HS_TITLE_DEFAULT_FEATURE  NSLocalizedStringFromTableInBundle(@"HS20111219113035", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Default title for the Health Summary feature.@LENGTH@17 characters@CONSTRAINTS@10 characters per word")
#define STR_HS_TITLE_ALLERGIES  NSLocalizedStringFromTableInBundle(@"HS20111219113105", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Title for the allergies section of Health Summary@LENGTH@22 characters")
#define STR_HS_TITLE_IMMUNIZATIONS  NSLocalizedStringFromTableInBundle(@"HS20111219113122", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Title for the Immunizations section of Health Summary@LENGTH@22 characters")
#define STR_HS_TITLE_HEALTH_ISSUES  NSLocalizedStringFromTableInBundle(@"HS20111219113148", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Title for the problem list section of Health Summary.@LENGTH@22 characters")
#define STR_HS_OVERLAY_LOADING  NSLocalizedStringFromTableInBundle(@"HS20111219113211", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Message displays as a section of the health summary is downloading its data from the server.@LENGTH@22 characters")
#define STR_HS_MESSAGE_NO_ALLERGIES  NSLocalizedStringFromTableInBundle(@"HS20111219113253", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Displays when the app confirms the selected patient has no allergies on file.@LENGTH@45 characters")
#define STR_HS_MESSAGE_NO_HEALTH_ISSUES  NSLocalizedStringFromTableInBundle(@"HS20111219113338", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Displays when the app confirms the selected patient has no issues on his problem list.@LENGTH@45 characters")
#define STR_HS_DETAIL_NOTED_ON  NSLocalizedStringFromTableInBundle(@"HS20111219113519", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Displays the date on which this item was added to the problem list.  %1$@ is the date in localized format.")
#define STR_HS_ACC_TITLE_HINT  NSLocalizedStringFromTableInBundle(@"HS20140912053417", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@This is the accessiblity hint for the Health Summary title. It informs user about the tab located at the bottom of screen that a user can use to switch between allergies, immunizations and health issues.")
#define STR_HS_ACC_ALLERGY_DETAILS_REACTION  NSLocalizedStringFromTableInBundle(@"HS20140912053537", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@This is the label for the list of reactions for a given allergy. Voiceover will read this label first and then the list of reactions. %1$@ is the list of reactions for a given allergy.")
#define STR_HS_ACC_TITLE_WITH_ALLERGIES  NSLocalizedStringFromTableInBundle(@"HS20140915103828", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Voiceover text for health summary feature title. The title text also tells user that allergies information is loaded currently.%1$@ is the title text.")
#define STR_HS_ACC_TITLE_WITH_IMMUNIZATIONS  NSLocalizedStringFromTableInBundle(@"HS20140915104125", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Voiceover text for health summary feature title. The title text also tells user that immunization information is loaded currently.%1$@ is the title text.")
#define STR_HS_ACC_TITLE_WITH_HEALTH_ISSUES  NSLocalizedStringFromTableInBundle(@"HS20140915104149", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Voiceover text for health summary feature title. The title text also tells user that health issues information is loaded currently.%1$@ is the title text.")
#define STR_HS_ACC_TITLE_ALG_IMM_HINT  NSLocalizedStringFromTableInBundle(@"HS20140925053403", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@This is the accessiblity hint for the Health Summary title. It informs user about the tab located at the bottom of screen that a user can use to switch between allergies and immunizations.")
#define STR_HS_ACC_TITLE_IMM_HS_HINT  NSLocalizedStringFromTableInBundle(@"HS20140925053540", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@This is the accessiblity hint for the Health Summary title. It informs user about the tab located at the bottom of screen that a user can use to switch between immunizations and health issues.")
#define STR_HS_ACC_TITLE_ALG_HS_HINT  NSLocalizedStringFromTableInBundle(@"HS20140925053554", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@This is the accessiblity hint for the Health Summary title. It informs user about the tab located at the bottom of screen that a user can use to switch between allergies and health issues.")
#define STR_HS_ACC_TITLE_WITH_IMMUNIZATIONS_WITH_PROXIES  NSLocalizedStringFromTableInBundle(@"HS20140925053949", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Voiceover text for health summary title. It reads the feature name along with the current mychart user (in case of proxies) followed by the current loaded tab (allergies or immunization or health issues). {0} is the title text. {1} is the patient's name.")
#define STR_HS_ACC_TITLE_WITH_ALLERGIES_FOR_PROXIES  NSLocalizedStringFromTableInBundle(@"HS20140925053654", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Voiceover text for health summary title. It reads the feature name along with the current mychart user (in case of proxies) followed by the current loaded tab (allergies or immunization or health issues). {0} is the title text. {1} is the patient's name.")
#define STR_HS_ACC_TITLE_WITH_HEALTH_ISSUES_WITH_PROXIES  NSLocalizedStringFromTableInBundle(@"HS20140925053952", @"HealthSummary", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Voiceover text for health summary title. It reads the feature name along with the current mychart user (in case of proxies) followed by the current loaded tab (allergies or immunization or health issues). {0} is the title text. {1} is the patient's name.")
