//
//  ScheduleStrings.h
//  MyChart
//
//  Copyright © 2010-2021 Epic Systems Corporation. All rights reserved.
//

#import "WPLocaleInfo.h"

#define STR_SCHED_HEADER_PROVIDER_SELECT  NSLocalizedStringFromTableInBundle(@"SCHED20111219121413", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Header for the provider selection screen accessed by hitting the "Provider and Location" button")
#define STR_SCHED_SELECTED_ALL_LOCATIONS  NSLocalizedStringFromTableInBundle(@"SCHED20111219122031", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Header for provider list for whom all applicable locations or centers will be searched for available appointments.")
#define STR_SCHED_HEADER_REASONS  NSLocalizedStringFromTableInBundle(@"SCHED20111219122240", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Header for the reason selection screen accessed by hitting the "Reason for Visit" button")
#define STR_SCHED_DEFAULT_OTHER_REASONS  NSLocalizedStringFromTableInBundle(@"SCHED20111219122308", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Tells the user that there may be additional selectable reasons available from the website (not Mobile).")
#define STR_SCHED_HINT_SELECT  NSLocalizedStringFromTableInBundle(@"SCHED20111219122356", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Indicates that nothing yet has been chosen for a field, and that pressing here will allow the user to select something.@LENGTH@35 characters")
#define STR_SCHED_BUTTON_BACK  NSLocalizedStringFromTableInBundle(@"SCHED20111219122555", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Button allows the user to return to the first scheduling page.@LENGTH@8 characters")
#define STR_SCHED_DEFAULT_EMERGENCY_NOTICE  NSLocalizedStringFromTableInBundle(@"SCHED20111219122629", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Tells the user that emergency issues should go through emergency services- scheduling appointments are for non-urgent matters only.@CONSTRAINTS@Maximum 2 lines, 29 characters per line")
#define STR_SCHED_OVERLAY_LOADING  NSLocalizedStringFromTableInBundle(@"SCHED20111219122712", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Appears while center/provider/reason data is being downloaded from the server.")
#define STR_SCHED_ALERT_TITLE_GENERIC_MAIN  NSLocalizedStringFromTableInBundle(@"SCHED20111219122751", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Generic alert title for when a user cannot cannot continue the scheduling workflow with the selected options.")
#define STR_SCHED_ALERT_BAD_REASON  NSLocalizedStringFromTableInBundle(@"SCHED20111219011606", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert appears when the patient cannot schedule an appointment for the selected reason.")
#define STR_SCHED_BUTTON_OK_MAIN  NSLocalizedStringFromTableInBundle(@"SCHED20111219011657", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Button closes an alert when no action is possible.")
#define STR_SCHED_ERROR_LOADING  NSLocalizedStringFromTableInBundle(@"SCHED20111219011718", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Appears when there is an error loading the available providers.")
#define STR_SCHED_ERROR_NO_PROVIDERS  NSLocalizedStringFromTableInBundle(@"SCHED20111219011752", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Error displays when there are no available providers.")
#define STR_SCHED_ALERT_NO_PROVIDERS_FOR_REASON  NSLocalizedStringFromTableInBundle(@"SCHED20111219011850", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert displays after a user selects a reason, but there aren't any providers available for an appointment for that reason.")
#define STR_SCHED_LABEL_REASON  NSLocalizedStringFromTableInBundle(@"SCHED20111219012115", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Label for the field in which the user selects a reason for the appointment he is scheduling.@LENGTH@27 characters")
#define STR_SCHED_LABEL_PROVIDER_LOCATION  NSLocalizedStringFromTableInBundle(@"SCHED20111219012159", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Label for the field in which the user selects the provider and location he wishes to schedule an appointment in.@LENGTH@27 characters")
#define STR_SCHED_ALERT_NO_REASON  NSLocalizedStringFromTableInBundle(@"SCHED20111219012226", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert displays after the user attempted to look for available appointment slots without selecting a reason for visit.")
#define STR_SCHED_ALERT_NO_PROVIDER  NSLocalizedStringFromTableInBundle(@"SCHED20111219012302", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert displays after the user attempted to look for available appointment slots without selecting a provider/location.")
#define STR_SCHED_OVERLAY_LOADING_MAIN  NSLocalizedStringFromTableInBundle(@"SCHED20111219012327", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Appears in the Providers and Locations field while the app is downloading available providers/locations from the server.@LENGTH@35 characters")
#define STR_SCHED_FIELD_ALL_LOCATIONS  NSLocalizedStringFromTableInBundle(@"SCHED20111219012512", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Displays if the user selected to search all locations for available appointment slots.")
#define STR_SCHED_FIELD_VARIOUS_LOCATIONS  NSLocalizedStringFromTableInBundle(@"SCHED20111219012547", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Displays in the Provider and Locations field if multiple locations were selected.")
#define STR_SCHED_OVERLAY_LOADING_SLOT  NSLocalizedStringFromTableInBundle(@"SCHED20111219012625", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Displays when loading initial information from the server regarding the selected slot.")
#define STR_SCHED_ALERT_NO_DETAILS  NSLocalizedStringFromTableInBundle(@"SCHED20111219012700", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Displays when slot information cannot be downloaded for some unknown reason.  Exiting this alert will bring the user back to the reason/provider selection screen.")
#define STR_SCHED_COMMENT_CHARACTERS_REMAINING  NSLocalizedStringFromTableInBundle(@"SCHED20111219012835", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Displays the maximum number of additional characters the user may use in the comment section while scheduling an appointment.  %1$@ is the number of characters remaining.@LENGTH@70 characters")
#define STR_SCHED_MESSAGE_COPAY_REFERRAL  NSLocalizedStringFromTableInBundle(@"SCHED20111219012955", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Warning that displays when there are no available providers.Indicates that the selected visit might have a higher copay due to the visit requiring a referral.")
#define STR_SCHED_MESSAGE_COPAY_COVERAGE  NSLocalizedStringFromTableInBundle(@"SCHED20111219013048", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Warning that indicates that the selected visit might have a higher copay due to a lack of coverage.")
#define STR_SCHED_MESSAGE_COPAY_NETWORK  NSLocalizedStringFromTableInBundle(@"SCHED20111219020510", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Warning that indicates that the selected visit might have a higher copay due to the selected provider being out of network.")
#define STR_SCHED_ALERT_TAKEN  NSLocalizedStringFromTableInBundle(@"SCHED20111219020539", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert tells the user that the selected appointment slot was recently taken.")
#define STR_SCHED_ALERT_SIMILAR  NSLocalizedStringFromTableInBundle(@"SCHED20111219020710", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert tells the user that the slot cannot be taken because a similar appointment is already scheduled.")
#define STR_SCHED_ALERT_CONFLICT  NSLocalizedStringFromTableInBundle(@"SCHED20111219020827", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert tells the user that the slot cannot be taken as the patient already has an appointment at that time.")
#define STR_SCHED_ALERT_TITLE_GENERIC_SLOT  NSLocalizedStringFromTableInBundle(@"SCHED20111219020858", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Generic title for an alert.")
#define STR_SCHED_BUTTON_OK_SLOT  NSLocalizedStringFromTableInBundle(@"SCHED20111219020934", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Button escapes an alert without making any changes.")
#define STR_SCHED_ALERT_TITLE_COMMENT  NSLocalizedStringFromTableInBundle(@"SCHED20111219020954", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert title for when a comment is required to schedule a time slot, but none was provided.")
#define STR_SCHED_ALERT_COMMENT  NSLocalizedStringFromTableInBundle(@"SCHED20111219021027", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert appears when a comment is required to schedule a time slot, but none was provided.")
#define STR_SCHED_OVERLAY_SCHEDULING  NSLocalizedStringFromTableInBundle(@"SCHED20111219021047", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Appears when a slot is being scheduled.")
#define STR_SCHED_ALERT_SUCCESS_CHECK  NSLocalizedStringFromTableInBundle(@"SCHED20111219021119", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert body for when we've successfully communicated scheduling an appointment slot to the server, but have not confirmed that we actually have the slot.  If for whatever reason, the scheduling fails, the user will receive communication.")
#define STR_SCHED_ALERT_SUCCESS  NSLocalizedStringFromTableInBundle(@"SCHED20111219021309", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert appears after successfully scheduling an appointment slot.  This scheduling has been confirmed.")
#define STR_SCHED_ALERT_TIMEOUT  NSLocalizedStringFromTableInBundle(@"SCHED20111219021336", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert body appears when the connection timed out while attempting to schedule a slot.")
#define STR_SCHED_ALERT_GENERIC_SLOT  NSLocalizedStringFromTableInBundle(@"SCHED20111219021410", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert appears when scheduling an appointment fails for an unknown reason.")
#define STR_SCHED_ALERT_TITLE_WARNING  NSLocalizedStringFromTableInBundle(@"SCHED20111219021438", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert title for a variety of warnings that don't block the scheduling of an appointment, but might make the user think twice.  This is usually due to a higher than expected copay.")
#define STR_SCHED_SCHEDULEBAR_DAYS_ONLINE  NSLocalizedStringFromTableInBundle(@"SCHED20111219021705", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Informs the user that he can browse dates further in the future online.  Appears in the date scroller on top of the page. Limit 3 lines, 15 characters per line.@LENGTH@45 characters")
#define STR_SCHED_HEADER_TIMES  NSLocalizedStringFromTableInBundle(@"SCHED20111219021749", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Header for the selecting a slot screen.@LENGTH@14 characters")
#define STR_SCHED_BUTTON_BACK_TIMES  NSLocalizedStringFromTableInBundle(@"SCHED20111219021954", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Allows the user to retreat to the selecting a provider/location/reason page.@LENGTH@8 characters")
#define STR_SCHED_ALL_LOCATIONS  NSLocalizedStringFromTableInBundle(@"SCHED20111219022020", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Appears when the user is searching all locations for available times.")
#define STR_SCHED_ALERT_TIMEOUT_TIMES  NSLocalizedStringFromTableInBundle(@"SCHED20111219022104", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert appears when the request for available times times out.")
#define STR_SCHED_ALERT_UPDATED  NSLocalizedStringFromTableInBundle(@"SCHED20111219022140", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert appears when the information available on the local device is out of date.")
#define STR_SCHED_ALERT_FAIL_TIMES  NSLocalizedStringFromTableInBundle(@"SCHED20111219022207", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert appears when finding available times fails for an unknown reason.")
#define STR_SCHED_ALERT_TITLE_GENERIC_TIMES  NSLocalizedStringFromTableInBundle(@"SCHED20111219022819", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Generic alert title for the selecting a time page.")
#define STR_SCHED_BUTTON_OK_TIMES  NSLocalizedStringFromTableInBundle(@"SCHED20111219022845", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Button exits an alert without making changes.")
#define STR_SCHED_ERROR_FOR_DATE  NSLocalizedStringFromTableInBundle(@"SCHED20111219024751", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@An unknown error occured when loading data for selected date. %1$@ is the date selected in local short format.")
#define STR_SCHED_NO_SLOTS_ON_DATE  NSLocalizedStringFromTableInBundle(@"SCHED20111219024855", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Appears when there are no available slots for a given date.  %1$@ is the date selected in local short format.")
#define STR_SCHED_BUTTON_FIND  NSLocalizedStringFromTableInBundle(@"SCHED20111219032049", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Hitting this button takes the user to the times selection page.  The results here are filtered by the reason and providers chosen above.@LENGTH@28 characters")
#define STR_SCHED_SECTION_HEADER_COMMENTS  NSLocalizedStringFromTableInBundle(@"SCHED20111219032123", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Label for the comments box for scheduling the selected slot.@LENGTH@47 characters")
#define STR_SCHED_BUTTON_SCHEDULE  NSLocalizedStringFromTableInBundle(@"SCHED20111219032217", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Button attempts to reserve the selected slot for an appointment.@LENGTH@33 characters")
#define STR_SCHED_WARNING_PREFIX  NSLocalizedStringFromTableInBundle(@"SCHED20111219035940", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Appears before the group of warnings associated with the selected slot.  Warnings are usually of higher-than-expected copays.")
#define STR_SCHED_ACC_PREV_MONTH_BUTTON  NSLocalizedStringFromTableInBundle(@"SCHED20140630052457", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@The voiceover text read for the button that scrolls the available appointments selected to the previous month.")
#define STR_SCHED_ACC_NEXT_MONTH_BUTTON  NSLocalizedStringFromTableInBundle(@"SCHED20140630052358", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@The voiceover text read for the button that scrolls the available appointments selected to the next month.")
#define STR_SCHED_REVIEW_TITLE  NSLocalizedStringFromTableInBundle(@"SCHED20140701023905", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Title for the slot review page. This is where a user reviews the information for their appointment one last time before scheduling.")
#define STR_SCHED_ACC_SCHEDULE_TITLE  NSLocalizedStringFromTableInBundle(@"SCHED20140703120939", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Voiceover text title for the scheduling view. This is read out loud to voiceover users instead of the standard title which in english abbreviates appointment for visual reasons.")
#define STR_SCHED_ACC_REVIEW_TITLE  NSLocalizedStringFromTableInBundle(@"SCHED20140703022225", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@The voiceover text read for the title of the scheduling review view. This is the view where you review the appointment details one last time before confirming the schedule.")
#define STR_SCHED_TITLE  NSLocalizedStringFromTableInBundle(@"SCHED20150611000002", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Title of scheduling activity")
#define STR_SCHED_REQUEST_SUCCESS  NSLocalizedStringFromTableInBundle(@"SCHED20150611000009", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Alert message shown when an appointment request has been successfully submitted")
#define STR_SCHED_BUTTON_CANCEL  NSLocalizedStringFromTableInBundle(@"STR_SCHED_BUTTON_CANCEL", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Button allows the user to retreat to the appointments list page.@LENGTH@8 characters")
#define STR_SCHED_RESCHEDULE_TITLE NSLocalizedStringFromTableInBundle(@"STR_SCHED_RESCHEDULE_TITLE", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Title displayed on the navigation bar of the rescheduling activity")
#define STR_SCHED_RESCHEDULED_APPT NSLocalizedStringFromTableInBundle(@"STR_SCHED_RESCHEDULED_APPT", @"Schedule", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Text displayed on the alert after reshceduling is complete.")

@interface WPScheduleStrings: NSObject

+ (NSString *) sectionHeaderComments;
+ (NSString *) warningPrefix;
+ (NSString *) slotDateTimeHeader;

@end
