//
//  WPTelemedicineStrings.h
//  MyChart
//
//  Copyright © 2013-2021 Epic Systems Corporation. All rights reserved.
//
#import "WPLocaleInfo.h"

#define STR_VID_WAIT_FOR  NSLocalizedStringFromTableInBundle(@"TEL20140108023400", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@The subtitle displayed in the video visit. Tells the user who the provider is. %1$@ is the provider name.@LENGTH@25 characters")
#define STR_VID_TEST_TITLE  NSLocalizedStringFromTableInBundle(@"TEL20140108023501", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@The title to display when the user is only testing their video connection and setup instead of actually joining a video conference with others.@LENGTH@30 characters")
#define STR_VID_TITLE_ERR  NSLocalizedStringFromTableInBundle(@"GEN11", @"General", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@The title displayed for general error messages.@LENGTH@20 characters")
#define STR_VID_ERR_MSG  NSLocalizedStringFromTableInBundle(@"TEL20140108023724", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@This is the error message displayed when the client is unable to receive necessary credentials to sign in, other than just the default user credentials. Occurs when there is a significant error with the server or web services.@LENGTH@100 characters")
#define STR_VID_HANG_UP  NSLocalizedStringFromTableInBundle(@"TEL20140108023749", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@The message displayed when the client is disconnecting from the video server and hanging up from the video conference.@LENGTH@30 characters")
#define STR_VID_AUDIO_OFF NSLocalizedStringFromTableInBundle(@"TEL20140210011111", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Message displayed to the user when the audio stream has been disabled during a video conference.@LENGTH@25 characters")
#define STR_VID_VIDEO_OFF NSLocalizedStringFromTableInBundle(@"TEL20140210011112", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Message displayed to the user when the video stream has been disabled during a video conference.@LENGTH@25 characters")
#define STR_VID_OK NSLocalizedStringFromTableInBundle(@"APPTS20111215040826", @"Appointments", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Button title to dismiss error messages.@LENGTH@25 characters")
#define STR_VID_CHECK_TITLE NSLocalizedStringFromTableInBundle(@"TEL20140212024003", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Title of the components check for video visit capabilities.")
#define STR_VID_CHECK_OK_MSG NSLocalizedStringFromTableInBundle(@"TEL20140212024004", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Message displayed when the video components check is ok.")
#define STR_VID_END_VIDEO_TITLE  NSLocalizedStringFromTableInBundle(@"APPTS20140108024601", @"Appointments", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@The title of the alert message that is displayed to stop the sign in process for video visits.@LENGTH@25 characters")
#define STR_VID_END_VIDEO_MSG  NSLocalizedStringFromTableInBundle(@"APPTS20140108024718", @"Appointments", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@The message of the alert displayed to stop the video sign in process. Asks the user if they really want to not sign into the video service.@LENGTH@100 characters")
#define STR_VID_CONT_VIDEO  NSLocalizedStringFromTableInBundle(@"APPTS20140108024807", @"Appointments", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@The text displayed on the button to continue signing in to the video service. Is displayed on the alert.@LENGTH@15 characters")
#define STR_VID_STOP_VIDEO  NSLocalizedStringFromTableInBundle(@"APPTS20140108024602", @"Appointments", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@The text displayed on the button to stop signing in to the video service. Is displayed on the alert.@LENGTH@15 characters")
#define STR_VID_PATIENT_ALREADY_IN  NSLocalizedStringFromTableInBundle(@"TEL20140210011113", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Title of the message displayed to the user when they are already signed on to the video conference with a different device so are unable to sign on on the current device. '\n' adds a new line.@LENGTH@200 characters")
#define STR_VID_BUTTON_TOGGLE_CAMERA  NSLocalizedStringFromTableInBundle(@"TEL20140409123001", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Accessibility text (read out loud by voice over) for the button that toggles between the front and back cameras.")
#define STR_VID_BUTTON_MUTE  NSLocalizedStringFromTableInBundle(@"TEL20140409123002", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Accessibility text (read out loud by voice over) for the button that mutes the microphone when microphone is on.")
#define STR_VID_BUTTON_HANG_UP  NSLocalizedStringFromTableInBundle(@"TEL20140409123003", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Accessibility text (read out loud by voice over) for the button that ends the video conference call.")
#define STR_VID_BUTTON_UNMUTE  NSLocalizedStringFromTableInBundle(@"TEL20140409123004", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Accessibility text (read out loud by voice over) for the button that mutes the microphone when microphone is off.")
#define STR_VID_BUTTON_UNMUTE_DISABLED  NSLocalizedStringFromTableInBundle(@"TEL20140409123005", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Accessibility text (read out loud by voice over) for the button that mutes the microphone when microphone is off and disabled.")
#define STR_VID_AUDIO_VIDEO_OFF NSLocalizedStringFromTableInBundle(@"TEL20140210011114", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Displayed during the video session when the audio and the video stream has been turned off. Used for both the remote status label and the local status.@LENGTH@40 characters")
#define STR_VID_DISCONNECTED_TITLE NSLocalizedStringFromTableInBundle(@"STR_VID_DISCONNECTED_TITLE", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Title of message displayed to the user when they have been forcibly disconnected from their video session (usually because they tried to logon to their visit from a different device).")
#define STR_VID_DISCONNECTED_MSG NSLocalizedStringFromTableInBundle(@"STR_VID_DISCONNECTED_MSG", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Message displayed to the user when they have been forcibly disconnected from their video session (usually because they tried to logon to their visit from a different device).")
#define STR_VID_LOST_INTERNET_MSG NSLocalizedStringFromTableInBundle(@"STR_VID_LOST_INTERNET_MSG", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Message displayed to the user when they have been forcibly disconnected from their video session because they lost internet connection.")
#define STR_VID_SYSTEM_AUDIO_OFF_LABEL NSLocalizedStringFromTableInBundle(@"STR_VID_SYSTEM_AUDIO_OFF_LABEL", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Message displayed to the user when the audio stream has been disabled during a video conference by another application (i.e. facetime) stealing the stream.@LENGTH@35 characters")
#define STR_VID_AUDIO_DISABLED_TITLE NSLocalizedStringFromTableInBundle(@"STR_VID_AUDIO_DISABLED_TITLE", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Title of message displayed to the user when the audio stream has been taken by another application (i.e. facetime) and they press the mute button.")
#define STR_VID_AUDIO_DISABLED_MSG NSLocalizedStringFromTableInBundle(@"STR_VID_AUDIO_DISABLED_MSG", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Message displayed to the user when the audio stream has been taken by another application (i.e. facetime) and they press the mute button.")
#define STR_VID_OUTSIDE_WINDOW_MSG NSLocalizedStringFromTableInBundle(@"STR_VID_OUTSIDE_WINDOW_MSG", @"Telemedicine", [WPLocaleInfo currentLocale].bundle, @"@CONTEXT@Message displayed if the user tries to join a video visit before the early start duration. %1$@ is the number of minutes in advance that the visit may be joined.")
#define STR_VID_MIC_NOT_GRABBED NSLocalizedStringFromTableInBundle(@"STR_VID_MIC_NOT_GRABBED", @"Telemedicine", [WPLocaleInfo currentLocale].bundle,@"@CONTEXT@Message displayed to users letting them know that Vidyo didn't successfully grab their mic.")
